export const data = [
  {
    id: "1",
    name: "karishma",
    profile: {
      firstName: "test",
      lastName: "react",
      empId: "108328786",
      role: "manager",
    },
    national: [
      {
        personId: "person id 1",
        startDate: "31/02/2019",
        country: "IND",
        cardType: "2",
        nationalId: "KJKDSHJ",
        isPrimary: "N",
        notes: "notes 1",
        attachment: "attachment 1",
        operation: "operation 1",
      },
      {
        personId: "person id 2",
        startDate: "31/02/2012",
        country: "IND",
        cardType: "4",
        nationalId: "KTRTYJ",
        isPrimary: "Y",
        notes: "notes 2",
        attachment: "attachment 2",
        operation: "operation 2",
      },
      {
        personId: "person id 3",
        startDate: "31/02/2015",
        country: "UAE",
        cardType: "7",
        nationalId: "JHJGHSHJ",
        isPrimary: "N",
        notes: "notes 2",
        attachment: "attachment 2",
        operation: "operation 2",
      },
    ],
    documents: [
      {
        type: "pan",
        image: "/avenir.png",
      },
      { type: "aadhar", image: "/main.jpeg" },
      { type: "passport", image: "/avenir.png" },
    ],
    imageUrl: "https://placeimg.com/300/300/any",
  },
  {
    id: "2",
    name: "sirisha",
    profile: {
      firstName: "test",
      lastName: "react",
      empId: "108328786",
      role: "engineer",
    },
    national: [
      {
        personId: "person id 1",
        startDate: "31/02/2019",
        country: "IND",
        cardType: "2",
        nationalId: "KJKDSHJ",
        isPrimary: "N",
        notes: "notes 1",
        attachment: "attachment 1",
        operation: "operation 1",
      },
      {
        personId: "person id 2",
        startDate: "31/02/2012",
        country: "IND",
        cardType: "4",
        nationalId: "KTRTYJ",
        isPrimary: "Y",
        notes: "notes 2",
        attachment: "attachment 2",
        operation: "operation 2",
      },
      {
        personId: "person id 3",
        startDate: "31/02/2015",
        country: "UAE",
        cardType: "7",
        nationalId: "JHJGHSHJ",
        isPrimary: "N",
        notes: "notes 2",
        attachment: "attachment 2",
        operation: "operation 2",
      },
    ],
    documents: [
      {
        type: "pan",
        image: "/avenir.png",
      },
      { type: "aadhar", image: "/main.jpeg" },
      { type: "passport", image: "/avenir.png" },
    ],
    imageUrl: "https://placeimg.com/300/300/any",
  },
  {
    id: "3",
    name: "pooja",
    profile: {
      firstName: "test",
      lastName: "react",
      empId: "108328786",
      role: "expert",
    },
    national: [
      {
        personId: "person id 1",
        startDate: "31/02/2019",
        country: "IND",
        cardType: "2",
        nationalId: "KJKDSHJ",
        isPrimary: "N",
        notes: "notes 1",
        attachment: "attachment 1",
        operation: "operation 1",
      },
      {
        personId: "person id 2",
        startDate: "31/02/2012",
        country: "IND",
        cardType: "4",
        nationalId: "KTRTYJ",
        isPrimary: "Y",
        notes: "notes 2",
        attachment: "attachment 2",
        operation: "operation 2",
      },
      {
        personId: "person id 3",
        startDate: "31/02/2015",
        country: "UAE",
        cardType: "7",
        nationalId: "JHJGHSHJ",
        isPrimary: "N",
        notes: "notes 2",
        attachment: "attachment 2",
        operation: "operation 2",
      },
    ],
    documents: [
      {
        type: "pan",
        image: "/avenir.png",
      },
      { type: "aadhar", image: "/main.jpeg" },
      { type: "passport", image: "/avenir.png" },
    ],
    imageUrl: "https://placeimg.com/300/300/any",
  },
];
